{
    "name": "Mobile Shop POS",
    "version": "19.0.1.0.0",
    "category": "Sales",
    "summary": "Mobile phone shop POS management system",
    "author": "Your Name",
    "license": "LGPL-3",
    "depends": [
        "base",
        "sale",
        "stock",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/product_category_data.xml",
        "data/sequence.xml",
        "views/pos_screen_views.xml",
        "views/mobile_shop_views.xml",
        "views/purchase_views.xml",
        "reports/sale_report.xml",
        "views/sale_views.xml",
        "views/sales_report_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "mobile_shop_pos/static/src/pos_screen/pos_screen.js",
            "mobile_shop_pos/static/src/pos_screen/pos_screen.xml",
            "mobile_shop_pos/static/src/pos_screen/pos_screen.scss",
            "mobile_shop_pos/static/src/pos_screen/pos_screen.scss",
            "mobile_shop_pos/static/src/products_screen/products_screen.js",
            "mobile_shop_pos/static/src/products_screen/products_screen.xml",
            "mobile_shop_pos/static/src/products_screen/products_screen.scss",
            "mobile_shop_pos/static/src/stock_screen/stock_screen.js",
            "mobile_shop_pos/static/src/stock_screen/stock_screen.xml",
            "mobile_shop_pos/static/src/stock_screen/stock_screen.scss",
        ],
    },
    "installable": True,
    "application": True,
    "auto_install": False,
}
